"""add password reset tokens table

Revision ID: 109f3b7e4383
Revises: dbfb6d480104
Create Date: 2026-03-28 15:10:06.344213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109f3b7e4383'
down_revision: Union[str, Sequence[str], None] = 'dbfb6d480104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("""
        CREATE TABLE IF NOT EXISTS password_reset_tokens (
            id UUID NOT NULL,
            user_id UUID NOT NULL,
            token VARCHAR NOT NULL,
            expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            used BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
            PRIMARY KEY (id),
            FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE,
            UNIQUE (token)
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
