"""add order_id to bookings

Revision ID: 22d0d45c7ea2
Revises: a3cefe8c0885
Create Date: 2026-08-14 08:41:37.773870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d0d45c7ea2'
down_revision: Union[str, Sequence[str], None] = 'a3cefe8c0885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('order_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'order_id')
    # ### end Alembic commands ###
