"""add payout_completed_at to orders

Revision ID: 35610401f0ca
Revises: e0c3baf9dd1f
Create Date: 2026-08-13 15:01:19.836958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35610401f0ca'
down_revision: Union[str, Sequence[str], None] = 'e0c3baf9dd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payout_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payout_completed_at')
    # ### end Alembic commands ###
