"""add chargeback evidence photos field

Revision ID: 50c20a752350
Revises: 4a69395e2a63
Create Date: 2026-06-05 14:28:08.918111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c20a752350'
down_revision: Union[str, Sequence[str], None] = '4a69395e2a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('chargeback_evidence_photos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'chargeback_evidence_photos')
    # ### end Alembic commands ###
