"""add type and link to notifications

Revision ID: 638c698571a8
Revises: f25d113d5f39
Create Date: 2026-09-05 20:23:40.934115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638c698571a8'
down_revision: Union[str, Sequence[str], None] = 'f25d113d5f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.Enum('payment', 'payout', 'order', 'booking', 'chargeback', 'message', 'system', name='notificationtype'), nullable=True))
    op.add_column('notifications', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'link')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
