"""add_chargeback_and_completion_proof_fields

Revision ID: 84eb437861ea
Revises: ae540c0a89c4
Create Date: 2026-05-14 19:49:21.879872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84eb437861ea'
down_revision: Union[str, Sequence[str], None] = 'ae540c0a89c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('completion_photos', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('completion_notes', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('buyer_accepted_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('chargeback_reason', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('chargeback_filed_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('chargeback_evidence_notes', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('chargeback_resolved_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('terms_accepted', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('terms_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'terms_version')
    op.drop_column('transactions', 'terms_accepted_at')
    op.drop_column('transactions', 'terms_accepted')
    op.drop_column('transactions', 'chargeback_resolved_at')
    op.drop_column('transactions', 'chargeback_evidence_notes')
    op.drop_column('transactions', 'chargeback_filed_at')
    op.drop_column('transactions', 'chargeback_reason')
    op.drop_column('orders', 'buyer_accepted_at')
    op.drop_column('orders', 'completed_at')
    op.drop_column('orders', 'completion_notes')
    op.drop_column('orders', 'completion_photos')
    # ### end Alembic commands ###
