"""add service_id to orders, make listing_id nullable

Revision ID: a3cefe8c0885
Revises: 35610401f0ca
Create Date: 2026-08-14 08:34:19.375914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cefe8c0885'
down_revision: Union[str, Sequence[str], None] = '35610401f0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('service_id', sa.UUID(), nullable=True))
    op.alter_column('orders', 'listing_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'orders', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'listing_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('orders', 'service_id')
    # ### end Alembic commands ###
