"""add payout_due_at to orders

Revision ID: e0c3baf9dd1f
Revises: 9c9c3ba0efba
Create Date: 2026-07-19 08:28:16.365393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c3baf9dd1f'
down_revision: Union[str, Sequence[str], None] = '9c9c3ba0efba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payout_due_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payout_due_at')
    # ### end Alembic commands ###
