"""add category_id to listings and services

Revision ID: e3462cfeab83
Revises: f30de51f0b84
Create Date: 2026-09-06 21:24:23.519410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3462cfeab83'
down_revision: Union[str, Sequence[str], None] = 'f30de51f0b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'listings', 'categories', ['category_id'], ['id'])
    op.add_column('services', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'services', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'category_id')
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'category_id')
    # ### end Alembic commands ###
