"""make legacy category column nullable

Revision ID: efb38e3ff80c
Revises: 92a9c9948003
Create Date: 2026-09-21 11:04:06.260202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb38e3ff80c'
down_revision: Union[str, Sequence[str], None] = '92a9c9948003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
